# -*- coding: utf-8 -*-
"""
Contém a lista completa de distribuidoras de energia elétrica
conforme o ANEXO I do Manual de Instruções da REN nº 1.095/2024 (ANEEL).

Formato: (Nome da Distribuidora, Código)
"""

LISTA_DISTRIBUIDORAS = [
    ("RGE (RGE SUL)", "1"),
    ("AmE (Amazonas Energia)", "2"),
    ("ENEL RJ", "3"),
    ("EDP SP", "4"),
    ("Roraima Energia", "5"),
    ("ESS", "6"),
    ("CEA", "7"),
    ("Equatorial AL (CEAL)", "8"),
    ("Neoenergia Brasília (CEB-DIS)", "9"),
    ("CEEE-D", "10"),
    ("CELESC-DIS", "11"),
    ("ENEL GO (CELG-D)", "12"),
    ("Equatorial PA (CELPA)", "13"),
    ("CELPE", "14"),
    ("ETO", "15"),
    ("Equatorial MA (CEMAR)", "16"),
    ("EMT", "17"),
    ("CEMIG-D", "18"),
    ("Equatorial PI (CEPISA)", "19"),
    ("ERO (CERON)", "20"),
    ("CHESP", "23"),
    ("CPFL Santa Cruz (Jaguari)", "24"),
    ("COCEL", "27"),
    ("COELBA", "28"),
    ("ENEL CE", "29"),
    ("COOPERALIANÇA", "30"),
    ("COPEL-DIS", "31"),
    ("COSERN", "32"),
    ("CPFL Paulista", "35"),
    ("CPFL Piratininga", "36"),
    ("DEMEI", "38"),
    ("DMED", "39"),
    ("EFLIC", "43"),
    ("EFLUL", "44"),
    ("ELEKTRO", "45"),
    ("EAC (ELETROACRE)", "46"),
    ("ELETROCAR", "47"),
    ("ENEL SP (ELETROPAULO)", "48"),
    ("ELFSM", "49"),
    ("EMR (EMG + ENF)", "50"),
    ("EMS", "51"),
    ("EPB (EPB + EBO)", "53"),
    ("EDP ES", "54"),
    ("ESE", "55"),
    ("FORCEL", "56"),
    ("HIDROPAN", "57"),
    ("DCELT (IENERGIA)", "58"),
    ("LIGHT", "59"),
    ("MUXENERGIA", "60"),
    ("SULGIPE", "62"),
    ("UHENPAL", "63"),
    ("CEREJ", "64"),
    ("CERAL", "65"),
    ("COORSEL", "66"),
    ("CERBRANORTE", "67"),
    ("CERAÇÁ", "68"),
    ("CERPALO", "69"),
    ("CERGRAL", "70"),
    ("CERSUL", "72"),
    ("COOPERA", "73"),
    ("COOPERMILA", "74"),
    ("CERGAL", "75"),
    ("CERTAJA", "76"),
    ("CERAL DIS", "77"),
    ("CERRP", "78"),
    ("CERNHE", "79"),
    ("CERES", "80"),
    ("CERCOS", "81"),
    ("CETRIL", "82"),
    ("CERPRO", "83"),
    ("CERMC", "84"),
    ("CERIS", "85"),
    ("CERIPA", "86"),
    ("CERIM", "87"),
    ("CEDRI", "88"),
    ("CEDRAP", "89"),
    ("CEPRAG", "90"),
    ("CERGAPA", "91"),
    ("CERILUZ", "92"),
    ("CERMISSÕES", "93"),
    ("CERMOFUL", "94"),
    ("CERTEL", "95"),
    ("CERTREL", "96"),
    ("COOPERCOCAL", "97"),
    ("COOPERLUZ", "98"),
    ("COPREL", "99"),
    ("CRELUZ-D", "100"),
    ("CRERAL", "101"),
    ("CEJAMA", "102"),
    ("CASTRO-DIS", "103"),
    ("CEGERO", "104"),
    ("CELETRO", "105"),
    ("CEMIRIM", "106"),
    ("CERAL ARARUAMA", "107"),
    ("CERCI", "108"),
    ("CERFOX", "109"),
    ("CERSAD", "110"),
    ("CERTHIL", "111"),
    ("CERVAM", "112"),
    ("CODESAM", "113"),
    ("COOPERNORTE", "114"),
    ("COOPERSUL", "115"),
    ("COOPERZEM", "116"),
]